//import DeviceKit
//
//extension Device {
//    var releaseDate: String {
//        switch self {
//#if os(iOS)
//        case .iPodTouch5: ""
//        case .iPodTouch6: ""
//        case .iPodTouch7: ""
//        case .iPhone4: ""
//        case .iPhone4s: ""
//        case .iPhone5: ""
//        case .iPhone5c: ""
//        case .iPhone5s: ""
//        case .iPhone6: ""
//        case .iPhone6Plus: ""
//        case .iPhone6s: ""
//        case .iPhone6sPlus: ""
//        case .iPhone7: ""
//        case .iPhone7Plus: ""
//        case .iPhoneSE: ""
//        case .iPhone8: ""
//        case .iPhone8Plus: ""
//        case .iPhoneX: ""
//        case .iPhoneXS: ""
//        case .iPhoneXSMax: ""
//        case .iPhoneXR: ""
//        case .iPhone11: ""
//        case .iPhone11Pro: ""
//        case .iPhone11ProMax: ""
//        case .iPhoneSE2: ""
//        case .iPhone12: ""
//        case .iPhone12Mini: ""
//        case .iPhone12Pro: ""
//        case .iPhone12ProMax: ""
//        case .iPhone13: ""
//        case .iPhone13Mini: ""
//        case .iPhone13Pro: ""
//        case .iPhone13ProMax: ""
//        case .iPhoneSE3: ""
//        case .iPhone14: ""
//        case .iPhone14Plus: ""
//        case .iPhone14Pro: ""
//        case .iPhone14ProMax: ""
//        case .iPhone15: ""
//        case .iPhone15Plus: ""
//        case .iPhone15Pro: ""
//        case .iPhone15ProMax: ""
//        case .iPhone16: ""
//        case .iPhone16Plus: ""
//        case .iPhone16Pro: ""
//        case .iPhone16ProMax: ""
//        case .iPad2: ""
//        case .iPad3: ""
//        case .iPad4: ""
//        case .iPadAir: ""
//        case .iPadAir2: ""
//        case .iPad5: ""
//        case .iPad6: ""
//        case .iPadAir3: ""
//        case .iPad7: ""
//        case .iPad8: ""
//        case .iPad9: ""
//        case .iPad10: ""
//        case .iPadAir4: ""
//        case .iPadAir5: ""
//        case .iPadAir11M2: ""
//        case .iPadAir13M2: ""
//        case .iPadMini: ""
//        case .iPadMini2: ""
//        case .iPadMini3: ""
//        case .iPadMini4: ""
//        case .iPadMini5: ""
//        case .iPadMini6: ""
//        case .iPadPro9Inch: ""
//        case .iPadPro12Inch: ""
//        case .iPadPro12Inch2: ""
//        case .iPadPro10Inch: ""
//        case .iPadPro11Inch: ""
//        case .iPadPro12Inch3: ""
//        case .iPadPro11Inch2: ""
//        case .iPadPro12Inch4: ""
//        case .iPadPro11Inch3: ""
//        case .iPadPro12Inch5: ""
//        case .iPadPro11Inch4: ""
//        case .iPadPro12Inch6: ""
//        case .iPadPro11M4: ""
//        case .iPadPro13M4: ""
//        case .homePod: "" //
//#elseif os(tvOS)
//        case .appleTVHD: ""
//        case .appleTV4K: ""
//        case .appleTV4K2: ""
//        case .appleTV4K3: ""
//#elseif os(watchOS)
//        case .appleWatchSeries0_38mm: ""
//        case .appleWatchSeries0_42mm: ""
//        case .appleWatchSeries1_38mm: ""
//        case .appleWatchSeries1_42mm: ""
//        case .appleWatchSeries2_38mm: ""
//        case .appleWatchSeries2_42mm: ""
//        case .appleWatchSeries3_38mm: ""
//        case .appleWatchSeries3_42mm: ""
//        case .appleWatchSeries4_40mm: ""
//        case .appleWatchSeries4_44mm: ""
//        case .appleWatchSeries5_40mm: ""
//        case .appleWatchSeries5_44mm: ""
//        case .appleWatchSeries6_40mm: ""
//        case .appleWatchSeries6_44mm: ""
//        case .appleWatchSE_40mm: ""
//        case .appleWatchSE_44mm: ""
//        case .appleWatchSeries7_41mm: ""
//        case .appleWatchSeries7_45mm: ""
//        case .appleWatchSeries8_41mm: ""
//        case .appleWatchSeries8_45mm: ""
//        case .appleWatchSE2_40mm: ""
//        case .appleWatchSE2_44mm: ""
//        case .appleWatchUltra: ""
//        case .appleWatchSeries9_41mm: ""
//        case .appleWatchSeries9_45mm: ""
//        case .appleWatchUltra2: ""
//        case .appleWatchSeries10_42mm: ""
//        case .appleWatchSeries10_46mm: ""
//#endif
//        case .simulator(let device): ""
//        case .unknown(let string): ""
//        }
//    }
//}
