import DeviceKit

extension Device {
    var supportsAppleIntelligence: Bool {
        switch self {
#if os(iOS)
        case .iPodTouch5: false
        case .iPodTouch6: false
        case .iPodTouch7: false
        case .iPhone4: false
        case .iPhone4s: false
        case .iPhone5: false
        case .iPhone5c: false
        case .iPhone5s: false
        case .iPhone6: false
        case .iPhone6Plus: false
        case .iPhone6s: false
        case .iPhone6sPlus: false
        case .iPhone7: false
        case .iPhone7Plus: false
        case .iPhoneSE: false
        case .iPhone8: false
        case .iPhone8Plus: false
        case .iPhoneX: false
        case .iPhoneXS: false
        case .iPhoneXSMax: false
        case .iPhoneXR: false
        case .iPhone11: false
        case .iPhone11Pro: false
        case .iPhone11ProMax: false
        case .iPhoneSE2: false
        case .iPhone12: false
        case .iPhone12Mini: false
        case .iPhone12Pro: false
        case .iPhone12ProMax: false
        case .iPhone13: false
        case .iPhone13Mini: false
        case .iPhone13Pro: false
        case .iPhone13ProMax: false
        case .iPhoneSE3: false
        case .iPhone14: false
        case .iPhone14Plus: false
        case .iPhone14Pro: false
        case .iPhone14ProMax: false
        case .iPhone15: false
        case .iPhone15Plus: false
        case .iPhone15Pro: true
        case .iPhone15ProMax: true
        case .iPhone16: true
        case .iPhone16Plus: true
        case .iPhone16Pro: true
        case .iPhone16ProMax: true
        case .iPad2: false
        case .iPad3: false
        case .iPad4: false
        case .iPadAir: false
        case .iPadAir2: false
        case .iPad5: false
        case .iPad6: false
        case .iPadAir3: false
        case .iPad7: false
        case .iPad8: false
        case .iPad9: false
        case .iPad10: false
        case .iPadAir4: false
        case .iPadAir5: false
        case .iPadAir11M2: true
        case .iPadAir13M2: true
        case .iPadMini: false
        case .iPadMini2: false
        case .iPadMini3: false
        case .iPadMini4: false
        case .iPadMini5: false
        case .iPadMini6: false
        case .iPadPro9Inch: false
        case .iPadPro12Inch: false
        case .iPadPro12Inch2: false
        case .iPadPro10Inch: false
        case .iPadPro11Inch: false
        case .iPadPro12Inch3: false
        case .iPadPro11Inch2: false
        case .iPadPro12Inch4: false
        case .iPadPro11Inch3: true
        case .iPadPro12Inch5: true
        case .iPadPro11Inch4: true
        case .iPadPro12Inch6: true
        case .iPadPro11M4: true
        case .iPadPro13M4: true
        case .homePod: false
#elseif os(tvOS)
        case .appleTVHD: false
        case .appleTV4K: false
        case .appleTV4K2: false
        case .appleTV4K3: false
#elseif os(watchOS)
        case .appleWatchSeries0_38mm: false
        case .appleWatchSeries0_42mm: false
        case .appleWatchSeries1_38mm: false
        case .appleWatchSeries1_42mm: false
        case .appleWatchSeries2_38mm: false
        case .appleWatchSeries2_42mm: false
        case .appleWatchSeries3_38mm: false
        case .appleWatchSeries3_42mm: false
        case .appleWatchSeries4_40mm: false
        case .appleWatchSeries4_44mm: false
        case .appleWatchSeries5_40mm: false
        case .appleWatchSeries5_44mm: false
        case .appleWatchSeries6_40mm: false
        case .appleWatchSeries6_44mm: false
        case .appleWatchSE_40mm: false
        case .appleWatchSE_44mm: false
        case .appleWatchSeries7_41mm: false
        case .appleWatchSeries7_45mm: false
        case .appleWatchSeries8_41mm: false
        case .appleWatchSeries8_45mm: false
        case .appleWatchSE2_40mm: false
        case .appleWatchSE2_44mm: false
        case .appleWatchUltra: false
        case .appleWatchSeries9_41mm: false
        case .appleWatchSeries9_45mm: false
        case .appleWatchUltra2: false
        case .appleWatchSeries10_42mm: false
        case .appleWatchSeries10_46mm: false
#endif
        case .simulator: false
        case .unknown: false
        }
    }
}
