import DeviceKit

extension Device {
    var power: String {
        switch self {
#if os(iOS)
        case .iPodTouch5: "3.8 Wh"
        case .iPodTouch6: "3.99 Wh"
        case .iPodTouch7: "3.99 Wh"
        case .iPhone4: ""
        case .iPhone4s: ""
        case .iPhone5: ""
        case .iPhone5c: ""
        case .iPhone5s: ""
        case .iPhone6: ""
        case .iPhone6Plus: ""
        case .iPhone6s: ""
        case .iPhone6sPlus: ""
        case .iPhone7: ""
        case .iPhone7Plus: ""
        case .iPhoneSE: ""
        case .iPhone8: ""
        case .iPhone8Plus: ""
        case .iPhoneX: ""
        case .iPhoneXS: ""
        case .iPhoneXSMax: ""
        case .iPhoneXR: ""
        case .iPhone11: ""
        case .iPhone11Pro: ""
        case .iPhone11ProMax: ""
        case .iPhoneSE2: ""
        case .iPhone12: ""
        case .iPhone12Mini: ""
        case .iPhone12Pro: ""
        case .iPhone12ProMax: ""
        case .iPhone13: ""
        case .iPhone13Mini: ""
        case .iPhone13Pro: ""
        case .iPhone13ProMax: ""
        case .iPhoneSE3: ""
        case .iPhone14: ""
        case .iPhone14Plus: ""
        case .iPhone14Pro: ""
        case .iPhone14ProMax: ""
        case .iPhone15: ""
        case .iPhone15Plus: ""
        case .iPhone15Pro: ""
        case .iPhone15ProMax: ""
        case .iPhone16: ""
        case .iPhone16Plus: ""
        case .iPhone16Pro: ""
        case .iPhone16ProMax: ""
        case .iPad2: "25 Wh"
        case .iPad3, .iPad4: "42.5 Wh"
        case .iPadAir: "32.9 Wh"
        case .iPadAir2: "27.62 Wh"
        case .iPad5, .iPad6, .iPad7: "32.9 Wh"
        case .iPadAir3: "30.8 Wh"
        case .iPad8, .iPad9: "32.4 Wh"
        case .iPad10: "28.6 Wh"
        case .iPadAir4, .iPadAir5: "28.6 Wh"
        case .iPadAir11M2: "28.93 Wh"
        case .iPadAir13M2: "36.59 Wh"
        case .iPadMini: "16.5 Wh"
        case .iPadMini2, .iPadMini3: "24.3 Wh"
        case .iPadMini4, .iPadMini5: "19.1 Wh"
        case .iPadMini6: "19.3 Wh"
        case .iPadPro9Inch: "27.91 Wh"
        case .iPadPro12Inch: "38.8 Wh"
        case .iPadPro12Inch2: "41.4 Wh"
        case .iPadPro10Inch: "30.8 Wh"
        case .iPadPro11Inch: "29.45 Wh"
        case .iPadPro12Inch3: "36.71 Wh"
        case .iPadPro11Inch2: "28.79 Wh"
        case .iPadPro12Inch4: "36.71 Wh"
        case .iPadPro11Inch3: "28.65 Wh"
        case .iPadPro12Inch5: "40.33 Wh"
        case .iPadPro11Inch4: "28.65 Wh"
        case .iPadPro12Inch6: "40.88 Wh"
        case .iPadPro11M4: "31.29 Wh"
        case .iPadPro13M4: "38.99 Wh"
        case .homePod: "" //
#elseif os(tvOS)
        case .appleTVHD: "410 Wh"
        case .appleTV4K: "-"
        case .appleTV4K2: "-"
        case .appleTV4K3: "-"
#elseif os(watchOS)
        case .appleWatchSeries0_38mm, .appleWatchSeries1_38mm: "0.78 Wh"
        case .appleWatchSeries0_42mm, .appleWatchSeries1_42mm: "0.93 Wh"
        case .appleWatchSeries2_38mm: "1.03 Wh"
        case .appleWatchSeries2_42mm: "1.27 Wh"
        case .appleWatchSeries3_38mm: "1 Wh (Cellular - 1.07 Wh)"
        case .appleWatchSeries3_42mm: "1.31 Wh (Cellular - 1.34 Wh)"
        case .appleWatchSeries4_40mm: "0.858 Wh"
        case .appleWatchSeries4_44mm: "1.113 Wh"
        case .appleWatchSeries5_40mm, .appleWatchSE_40mm: "0.944 Wh"
        case .appleWatchSeries5_44mm, .appleWatchSE_44mm: "1.129 Wh"
        case .appleWatchSeries6_40mm: "1.024 Wh"
        case .appleWatchSeries6_44mm: "1.17 Wh"
        case .appleWatchSeries7_41mm: "1.094 Wh"
        case .appleWatchSeries7_45mm: "1.189 Wh"
        case .appleWatchSeries8_41mm: "-"
        case .appleWatchSeries8_45mm: "-"
        case .appleWatchSE2_40mm: "-"
        case .appleWatchSE2_44mm: "-"
        case .appleWatchUltra: "-"
        case .appleWatchSeries9_41mm: "-"
        case .appleWatchSeries9_45mm: "-"
        case .appleWatchUltra2: "-"
        case .appleWatchSeries10_42mm: "-"
        case .appleWatchSeries10_46mm: "-"
#endif
        case .simulator: "-"
        case .unknown: "-"
        }
    }
}
